In [1]:
from cProfile import label
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import sympy as smp

from scipy.optimize import fsolve, root
from scipy.integrate import odeint
from scipy.integrate import solve_ivp
from scipy.integrate import quad
from mpl_toolkits import mplot3d
from sympy import *

In [ ]:
r0 = 1
alpha = 1
Gamma = 1.5
E = 0.1

In [ ]:
rc = fsolve(lambda rc: (2/(Gamma - 1) + 1/2) * rc / (4 * (rc - 1)**2) - rc / (2 * (rc - 1)) - E, 1.2)
rc

In [ ]:
def x_eq(x, y):
    out = x - (gamma - 1)/2 * (y/rc - 2/rc**2 + 1/(rc - 1)**3) / (2*x - 2*y)
    return out

def y_eq(x, y):
    out = y + (x/rc - 2/rc**2 + 1/(rc - 1)**3) / (2*x - 2*y)
    return out

def S_eq(S):
    x, y = S
    return [x_eq(x, y), y_eq(x, y)]


In [ ]:
sol1, sol2 = fsolve(S_eq, [-0.01, -0.8])

In [ ]:
x, y = symbols('x, y')
eq1 = x - (Gamma - 1)/2 * (y/rc - 2/rc**2 + 1/(rc - 1)**3) / (2*x - 2*y)
eq2 = y + (x/rc - 2/rc**2 + 1/(rc - 1)**3) / (2*x - 2*y)
sol = nsolve([eq1, eq2], [-0.01, -0.1])

In [ ]:
x, y = symbols('x, y')
eq1 = Eq((Gamma - 1)/2 * (y/rc - 2/rc**2 + 1/(rc - 1)**3) / (2*x - 2*y), x)
eq2 = Eq((x/rc - 2/rc**2 + 1/(rc - 1)**3) / (2*x - 2*y), - y )
sol = nsolve([eq1, eq2], [x, y], [-0.01, -0.8])

In [ ]:
x = symbols("x")
x**2

In [ ]:
def func(x):
    return [x[0] * np.cos(x[1]) - 4,
            x[1] * x[0] - x[1] - 5]
root = fsolve(func, [1, 1])
root

In [ ]:
def Solve(S):
    x = S[0]
    y = S[1]
    out1 = x - (Gamma - 1)/2 * (y/rc - 2/rc**2 + 1/(rc - 1)**3) / (2*x - 2*y)
    out2 = y + (x/rc - 2/rc**2 + 1/(rc - 1)**3) / (2*x - 2*y)
    return [out1, out2]

root = fsolve(Solve, [-0.01, -0.8])
root


In [ ]:
def Crit(rc):
    out = (2/(Gamma - 1) + 1/2) * (rc*r0)/(4*(rc - r0)**2) - rc/(2*(rc - r0)) - E
    return out

In [ ]:
sol = fsolve(Crit, 1.5)
rc = sol
rc

In [ ]:
cs_crit = np.sqrt(rc*r0/(4*(rc - r0)**2))
vr_crit = cs_crit

In [ ]:
def der(S):
    dcdr, dvdr = S
    num1 = dcdr - (Gamma - 1)/2 * (4*vr_crit*dvdr/rc - 2*vr_crit**2/rc**2 + r0/(rc - r0)**3)
    den1 = dcdr - 2*dvdr + dcdr
    out1 = num1/den1
    num2 = dvdr - (4*cs_crit*dcdr/rc - 2*cs_crit**2/rc**2 + r0/(rc - r0)**3)
    den2 = dvdr - 2*dcdr + dvdr
    out2 = num2/den2
    return [out1[0], out2[0]]

print(der([1, 4]))

In [ ]:
ini_guess = (-0.02, -0.2)
der_crit = fsolve(der, ini_guess)
der_crit

In [ ]:
r, v, dvdr, c, dcdr, L, F, dFdr, g = symbols('r, v, dvdr, c, dcdr, L, F, dFdr, g')
r**(1/2)

In [ ]:
L/F

In [ ]:
solution = solve((r*dvdr/v + (g + 1)*r*dcdr/(c*(g - 1)) + 3/2 - r*dFdr/(2*F), v*dvdr + 2*c*dcdr/(g - 1) - L**2/r**3 + F), (dcdr, dvdr))
solution[dcdr]

In [9]:
#Defining the variables
r, a = smp.symbols('r, a')
num = (r**2 - 2*a*smp.sqrt(r) + a**2)**2
den = r**3 * (smp.sqrt(r)*(r - 2) + a)**2
force_sym = num/den

#Creating the force function
Force = smp.lambdify((r, a), force_sym)
dFdr = lambdify((r, a), diff(force_sym, r))

In [ ]:
Force((2, 3))

In [ ]:
integrate(force_sym, (r, 2, smp.oo))

In [ ]:
dFdr((2, 3))

In [20]:
def f(x):
    return 1/(1 + x**2)

In [22]:
quad(f, -np.inf, np.inf)

(3.141592653589793, 5.155583041103855e-10)

In [27]:
A = 3
quad(dFdr, 1, np.inf, args=(A))

(-4.000000000004042, 1.3481761373592902e-08)

In [3]:
force_sym

(a**2 - 2*a*sqrt(r) + r**2)**2/(r**3*(a + sqrt(r)*(r - 2))**2)

In [4]:
diff(force_sym, r)

(-2*a/sqrt(r) + 4*r)*(a**2 - 2*a*sqrt(r) + r**2)/(r**3*(a + sqrt(r)*(r - 2))**2) + (-2*sqrt(r) - (r - 2)/sqrt(r))*(a**2 - 2*a*sqrt(r) + r**2)**2/(r**3*(a + sqrt(r)*(r - 2))**3) - 3*(a**2 - 2*a*sqrt(r) + r**2)**2/(r**4*(a + sqrt(r)*(r - 2))**2)

In [6]:
#Creating the force function
def Force(r, a):
    num = (r**2 - 2*a*np.sqrt(r) + a**2)**2
    den = r**3 * (np.sqrt(r)*(r - 2)**2 + a)**2
    return num/den

#Creating the Derivative of force function
def dFdr(r, a):
    num1 = (r**2 - 2*a*np.sqrt(r) + a**2)*(- 2*a/np.sqrt(r) + 4*r)
    den1 = r**3 * (np.sqrt(r)*(r - 2)**2 + a)**2
    num2 =  (r**2 - 2*a*np.sqrt(r) + a**2)**2 * (- 2*np.sqrt(r) - (r - 2)/np.sqrt(r))
    den2 = r**3 * (np.sqrt(r)*(r - 2)**2 + a)**3
    num3 = - 3 * (r**2 - 2*a*np.sqrt(r) + a**2)**2
    den3 = r**4 * (np.sqrt(r)*(r - 2)**2 + a)**2
    return num1/den1 + num2/den2 + num3/den3

#Creating the Potential function
def Potential(r, a):
    return quad(Force, r, np.inf, args=(a))[0]

In [34]:
Force(1.5, 0.1)
dFdr(1.5, 0.1)
Potential(3, 0.95)

0.12320535017838374

In [8]:
Gamma = 1.5
a = 0.95
L = 0.1
E = 1

In [16]:
def Crit(rc):
    out = (2*Gamma/(Gamma - 1)) * ((L**2/rc**3 - Force(rc, a)) / (dFdr(rc, a) / Force(rc, a) - 3/rc)) + Potential(rc, a) + L**2/(2*rc**2) - E
    return out

In [30]:
Crit(2.878)

0.0003491784359368477

In [28]:
rc = fsolve(Crit, 2.5)
rc

array([2.87826183])

In [2]:
v, r = symbols('v, r')
diff(v, r)

0

In [5]:
def test(x, y, z):
    return x**2 -2*y + z

x = fsolve(test, 1, args=(2, 4))
x

array([9.25035823e-09])

In [10]:
diff(force_sym, r, 2)

((a/r**(3/2) + 4)*(a**2 - 2*a*sqrt(r) + r**2) + 2*(a/sqrt(r) - 2*r)**2 + 4*(2*sqrt(r) + (r - 2)/sqrt(r))*(a/sqrt(r) - 2*r)*(a**2 - 2*a*sqrt(r) + r**2)/(a + sqrt(r)*(r - 2)) + (3*(2*sqrt(r) + (r - 2)/sqrt(r))**2/(a + sqrt(r)*(r - 2)) - (4 - (r - 2)/r)/sqrt(r))*(a**2 - 2*a*sqrt(r) + r**2)**2/(2*(a + sqrt(r)*(r - 2))) + 12*(a/sqrt(r) - 2*r)*(a**2 - 2*a*sqrt(r) + r**2)/r + 6*(2*sqrt(r) + (r - 2)/sqrt(r))*(a**2 - 2*a*sqrt(r) + r**2)**2/(r*(a + sqrt(r)*(r - 2))) + 12*(a**2 - 2*a*sqrt(r) + r**2)**2/r**2)/(r**3*(a + sqrt(r)*(r - 2))**2)

In [14]:
dFdr2 = lambdify((r, a), diff(force_sym, r, 2) - 3.4865)

In [15]:
dFdr2(2, 0.9)

6.5064034453499175e-06

In [16]:
fsolve(dFdr2, 1.8, args=(0.9))

array([2.0000005])